# Generated by Django 4.2.5 on 2023-09-06 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=975)),
                ('dev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_developers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='IssueGameTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=190)),
                ('bug_description', models.CharField(max_length=3190)),
                ('expected_result', models.CharField(max_length=13490)),
                ('repeat_step', models.CharField(max_length=1990)),
                ('file_proof', models.FileField(upload_to='uploads/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_issues', to='ezlifenubapi.game')),
                ('qa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_testers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezlifenubapi.game')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezlifenubapi.genre')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(through='ezlifenubapi.GameGenre', to='ezlifenubapi.game'),
        ),
    ]
